version: "3"
services:
  mongodb0:
    image: mongo:5.0-focal
    container_name: mongodb0-container
    restart: unless-stopped
    command: --replSet rs0 --dbpath /home/data --oplogSize 128
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
    networks:
      - my-networks
    volumes:
      - "./rs0-0:/home/data"
      - "./replicaSet.js:/home/replicaSet.js:ro"
  mongodb1:
    image: mongo:5.0-focal
    container_name: mongodb1-container
    command: --replSet rs0 --dbpath /home/data --oplogSize 128
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
    networks:
      - my-networks
    volumes:
      - "./rs0-1:/home/data"
  mongodb2:
    image: mongo:5.0-focal
    container_name: mongodb2-container
    command: --replSet rs0 --dbpath /home/data --oplogSize 128
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
    networks:
      - my-networks
    volumes:
      - "./rs0-2:/home/data"
networks:
  my-networks: